### ISSUE TITLE
Return both alleles rather than single genotype/haplotype

### ISSUE THREAD

**Issue by pdimens** [OpenMendel/VCFTools.jl#15]
I'm looking to rewrite the VCF file importer for `PopGen.jl` and the genotype format used by the package is in the form `(allele1, allele2)`, so I'm hoping to find an option preserving the raw allele information. Reading through the documentation, it's clear there are functions `convert_gt` and `convert_ht` to generate a matrix of genotypes or haplotypes respectively, however each of those functions return a single value per sample per locus. Is there a function/method/API to return a matrix for each allele? Such as, return two matrices, one for the first of two alleles for each sample, the other for the second of two alleles for each sample?

**Comment by biona001** [comment]
Actually `convert_ht` does return 2 values per locus: the first row is haplotype 1, and second row is haplotype 2. If you want 2 matrices as you described, you can do:
```
H = convert_ht(Float64, "your_vcf_file.vcf.gz")
H1 = view(H, 1:2:size(H, 1), :) # allele1
H2 = view(H, 2:2:size(H, 1), :) # allele2
```
Also, note `convert_ht` **does not** check whether your genotype is phased, so use with caution...

**Comment by pdimens** [comment]
Oh, I understand now, thanks! Serves me right for looking at the docs without trying it for myself 😅
