### ISSUE TITLE
Any plan to update to Julia v1?

### ISSUE THREAD

**Issue by gtollefson** [OpenMendel/VCFTools.jl#2]
No issue to report in Julia v0.6 - but am wondering if there are plans to update this package to be compatible with Julia v1. 

We're using this package in a visualization package and bioinformatics tool. We'd like to release a v1 supported version of our tool and would like to include functionality supported by this package.

**Comment by Hua-Zhou** [comment]
Thanks for the interest, @gtollefson We are busy updating the OpenMendel packages at the moment. VCFTools.jl definitely is in the pipeline. I estimate it'll be done within 2-3 weeks.

**Comment by gtollefson** [comment]
Fantastic!

**Comment by biona001** [comment]
Can I try to tackle this issue?

**Comment by Hua-Zhou** [comment]
That'll be great for you to help upgrade the code to Julia v1.0+, Ben!

**Comment by biona001** [comment]
As of 767800b, Julia 1.0 and 1.3 is officially supported. Nightly version currently passes Travis test as well.
