### ISSUE TITLE
REF/ALT allele flipped

### ISSUE THREAD

**Issue by biona001** [OpenMendel/VCFTools.jl#6]
According to [VCF file documentation](https://samtools.github.io/hts-specs/VCFv4.2.pdf) (bottom of page 5), `0/0` should mean REF/REF, `0/1` is REF/ALT, and `1/1` is ALT/ALT. According to [VCFTools.jl's documentation](https://biona001.github.io/VCFTools.jl/dev/man/convert/#Genetic-model-1), it is the opposite:

![Screen Shot 2020-01-15 at 12 22 59 PM](https://user-images.githubusercontent.com/16760873/72468371-d9acfd80-3791-11ea-9ef5-9ca231d18b56.png)

This makes a difference when computing summary statistics. I'm very inclined on flipping this in the code now, but it affects a surprisingly large fraction of the code, so I want to make sure we want to do this before I start.

**Comment by Hua-Zhou** [comment]
I agree it's better to be consistent with VCF specification. That requires going through the codebase and documentation to be consistent with this convention.

**Comment by biona001** [comment]
this is fixed by 767800b
