### ISSUE TITLE
Travis failed on Julia v1.4 and nightly on Linux

### ISSUE THREAD

**Issue by Hua-Zhou** [OpenMendel/VCFTools.jl#9]
<https://travis-ci.org/github/OpenMendel/VCFTools.jl/builds/670858865>

`convert to transpose functions` step in test script `convert_test.jl`

**Comment by biona001** [comment]
Fixed by b1032fec2a51ad8f5766e952c5e020ec8f72b06b. All test pass on [travis](https://travis-ci.org/OpenMendel/VCFTools.jl), although badge is not updating for some reason.
